In [2]:
import numpy as np

In [8]:
arr = np.array((1,2,3,'a'))
arr

array(['1', '2', '3', 'a'], dtype='<U11')

In [18]:
lis = [1,2,3]
print(f"list+list: {lis+[4,5,6]}")

arr = np.array((1,2,3))
lst_arr = arr + [4,5,6]
print(f"arr + list: {lst_arr}")
print(f"type(list+array) = {type(lst_arr)}")

list+list: [1, 2, 3, 4, 5, 6]
arr + list: [5 7 9]
type(list+array) = <class 'numpy.ndarray'>


In [22]:
print(arr/2)
print(arr**2)
print(arr*5)
print(arr + [5])
try:
    arr + [1,2] #=> ValueError
except ValueError as e:
    print(e)

[0.5 1.  1.5]
[1 4 9]
[ 5 10 15]
[6 7 8]
operands could not be broadcast together with shapes (3,) (2,) 


In [32]:
print(np.tanh(arr))
print(np.cos(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))


[0.76159416 0.96402758 0.99505475]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [38]:
arr2 = np.array([4,5,6])
print(np.sum(arr2*arr))
print(arr2.dot(arr))
print(arr2 @ arr)

32
32
32


In [40]:
a,b = arr,arr2
cosangle = a@b/(np.linalg.norm(a)*np.linalg.norm(b))
angle_degree= np.rad2deg(np.arccos(cosangle))
degree_sign= u'\N{DEGREE SIGN}'
print(f"{angle_degree}{degree_sign}")

12.933154491899135°


In [45]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [49]:
print(arr[0][0])
print(arr[0,0])


1
1


In [51]:
arr[:,0]

array([1, 3])

In [58]:
print(f"inverse of arr: ")
print(np.linalg.inv(arr))
print("determinant of arr:")
print(np.linalg.det(arr))
print("arr Transpose:")
print(arr.T)
print("trace of a:")
print(np.trace(arr))


inverse of arr: 
[[-2.   1. ]
 [ 1.5 -0.5]]
determinant of arr:
-2.0000000000000004
arr Transpose:
[[1 3]
 [2 4]]
trace of a:
5


In [61]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr.dot(arr2)


array([[ 9, 12, 15],
       [19, 26, 33]])

In [63]:
# a^(-1)*a == I ?
np.linalg.inv(arr).dot(arr) == np.array([[1,0],[0,1]])

array([[False,  True],
       [False,  True]])

In [64]:
np.allclose(np.linalg.inv(arr).dot(arr) , np.array([[1,0],[0,1]]))

True